name: checks
on:
  push:
  pull_request:
jobs:
  md-and-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Lint (ruff)
        run: ruff check .
